unknown_threshold: 0.60
window_size: 5

bins:
  recycle:
    - lp_cup_lids
    - lp_plastic_cup
    - rigid_plastic_container
    - rigid_plastic_lid
    - small_plastic_container

  compost:
    - lp_paper_cup
    - napkin

  landfill:
    - straw
    - utensil
