unknown_threshold: 0.60
window_size: 5

bins:
  bottles:
    - lp_plastic_cup

  compost:
    - lp_paper_cup
    - napkin
    - straw
    - utensil
    - lp_cup_lids

  landfill:
    - small_plastic_container
    - rigid_plastic_container
    - rigid_plastic_lid
    
